"""人类可读测试报表用的 case 元数据。

key = pytest 函数名（不含参数化后缀）。参数化 case 共用同一条说明，
明细里会带上完整 nodeid。
"""

from __future__ import annotations

from typing import Any

# kind: offline_unit | offline_mock | offline_fixture | live_network
# module: 业务域标签

CASES: dict[str, dict[str, Any]] = {
    # ── api_contracts ──────────────────────────────────────────────
    "test_split_code_honors_explicit_exchange": {
        "module": "符号解析",
        "kind": "offline_unit",
        "entry": "scutio_data.core.split_code / get_prefix / normalize_code",
        "feature": "显式 SH/SZ/BJ 前缀不被按数字规则改写；裸 000xxx 默认深市",
        "input": (
            "代码串：sh000001、000001.SH、SH.000001、sh000300、sh000688、"
            "000001、399001、600519、899050"
        ),
        "expected": (
            "显式前缀 → 对应 (sh|sz|bj, 六位码)；"
            "裸 000001 → (sz, 000001) 不当上证指数；600519→sh；899050→bj"
        ),
    },
    "test_split_code_hong_kong_markers": {
        "module": "符号解析",
        "kind": "offline_unit",
        "entry": "scutio_data.core.split_code",
        "feature": "港股需显式标记；腾讯类代码补足 5 位；裸 5 位不得默认真港股",
        "input": "hk02513、HK02513、02513.HK、HK.02513、hk700、00700.HK；裸 02513",
        "expected": "前缀码 → (hk, 补齐码)；get_prefix/normalize 正确；裸 02513 抛 ValueError",
    },
    "test_parse_news_time_and_rank": {
        "module": "新闻",
        "kind": "offline_unit",
        "entry": "scutio_data.feeds.parse_news_time / rank_stock_news_items",
        "feature": "时间解析、噪音过滤、time/relevance 排序",
        "input": "构造条目（榜单噪音 + 含码/名稿）",
        "expected": "drop_noise 剔除榜单；time 新→旧；relevance 分可用",
    },
    "test_news_contracts": {
        "module": "新闻",
        "kind": "offline_mock",
        "entry": "scutio_data.feeds.stock_news",
        "feature": "个股新闻解析字段归一 + 排序信封",
        "input": "mock AKShare 个股新闻行",
        "expected": "title/content/time/source/url/relevance；信封 order/drop_noise",
    },
    "test_fundamental_and_flow_contracts": {
        "module": "基本面 / 资金",
        "kind": "offline_mock",
        "entry": "scutio_data.fundamentals / capital",
        "feature": "基本面、两融、大宗、分红、资金流等字段契约稳定",
        "input": "mock AKShare 基本面、历史快照与日频资金行",
        "expected": "关键键齐全；金额/日期类型合理；ok 信封正确",
    },
    "test_industry_comparison_fetches_gainers_and_losers": {
        "module": "行业对比",
        "kind": "offline_mock",
        "entry": "scutio_data.capital.industry_comparison",
        "feature": "全行业表排序得到真正的涨跌两端",
        "input": "mock AKShare 全行业表",
        "expected": "top/bottom 两边都有数据；bottom 为真正跌幅股",
    },
    "test_industry_comparison_partial_success": {
        "module": "行业对比",
        "kind": "offline_mock",
        "entry": "industry_comparison",
        "feature": "缺失涨跌幅不当作零进入榜单",
        "input": "mock：有效涨跌幅与空值混合",
        "expected": "保留有效行，披露剔除行数",
    },
    "test_industry_comparison_both_legs_fail": {
        "module": "行业对比",
        "kind": "offline_mock",
        "entry": "industry_comparison",
        "feature": "行业数据源均失败时返回空列表且 ok=False",
        "input": "mock：AKShare 行业源均失败",
        "expected": "ok=False；列表为空；error 非空",
    },
    "test_industry_comparison_sina_fallback": {
        "module": "行业对比",
        "kind": "offline_mock",
        "entry": "capital.industry_comparison + _providers.akshare.client.fetch",
        "feature": "东财失败时使用 AKShare 新浪行业榜，保留分类差异",
        "input": "mock AKShare 东财失败、新浪公司家数与领涨数据",
        "expected": "ok=true、source=sina_industry；top/bottom 按涨跌幅取端",
    },
    "test_security_quote_and_bars_fallback_envelope": {
        "module": "行情多源",
        "kind": "offline_mock",
        "entry": "scutio_data.market.security_quote / security_bars",
        "feature": "报价多源合并；K 线 AKShare 新浪失败时降级 AKShare 东财，错误源写入信封",
        "input": (
            "quote: [600519, 000001]，腾讯+新浪 mock；"
            "bars: 600519 count=1，AKShare 新浪抛错、东财返回 1 根 close=1.5"
        ),
        "expected": (
            "quote ok=true、含腾讯源；"
            "bars ok=true、source=akshare_eastmoney、close=1.5、errors 含 akshare_sina"
        ),
    },
    "test_mutual_type_and_southbound_mapping": {
        "module": "资金映射",
        "kind": "offline_unit",
        "entry": "scutio_data.capital.flows._mutual_type_code / MUTUAL_TYPE",
        "feature": "北向/南向/港股通 type 码稳定",
        "input": "别名：south、港股通、ggt_sh、north、sgt",
        "expected": "south/港股通→006；ggt_sh→002；north→005；sgt→003",
    },
    "test_tencent_quote_prefers_explicit_index_prefix": {
        "module": "腾讯报价",
        "kind": "offline_mock",
        "entry": "scutio_data.market.tencent_quote",
        "feature": "sh000001 请求上证综指，不误成 sz000001",
        "input": "code=sh000001（及对照），mock 抓实际请求 symbol",
        "expected": "请求串含 sh000001 / 上证侧前缀，而非深市 000001",
    },
    "test_tencent_quote_keeps_colliding_index_and_stock": {
        "module": "腾讯报价",
        "kind": "offline_mock",
        "entry": "scutio_data.market.tencent_quote",
        "feature": "指数 sh000001 与个股 000001 批量请求时互不覆盖",
        "input": "批量 [sh000001, 000001]，mock 双行返回",
        "expected": "结果中两条键/记录并存，代码不混淆",
    },
    # ── exchange_ids ───────────────────────────────────────────────
    "test_em_secid_uses_split_code_not_startswith_6_only": {
        "module": "交易所 ID",
        "kind": "offline_unit",
        "entry": "_providers.eastmoney.em_secid / em_src_security_code",
        "feature": "东财 secid 走 split_code，不靠 startswith('6')；5xxxxx 归沪",
        "input": "600519/sh600519/510050/000001/899050 等",
        "expected": "沪 1.xxxxxx；深/京 0.xxxxxx；em_src 前缀正确",
    },
    "test_financial_report_hk_pivots_line_items": {
        "module": "基本面",
        "kind": "offline_mock",
        "entry": "fundamentals.financial_report",
        "feature": "港股三表东财长表 pivot 为宽表",
        "input": "hk00700 lrb annual，mock AKShare 东财财报长表",
        "expected": "两期年报；含营业额等科目",
    },
    "test_financial_report_us_pivots_and_resolves_secucode": {
        "module": "基本面",
        "kind": "offline_mock",
        "entry": "fundamentals.financial_report",
        "feature": "美股三表向 AKShare 传入 ticker、表类型和年报口径",
        "input": "usTSLA fzb annual，mock AKShare 东财财报长表",
        "expected": "两期 FY；含现金科目",
    },
    # ── package_paths ──────────────────────────────────────────────
    "test_find_scripts_dir_from_package_layout": {
        "module": "路径运行时",
        "kind": "offline_unit",
        "entry": "scutio_data.paths.find_scripts_dir / ensure_on_syspath",
        "feature": "从包布局定位 scripts 目录并注入 sys.path",
        "input": "当前安装/源码树布局",
        "expected": "找到含 scutio_data 的 scripts 目录；sys.path 含该路径",
    },
    "test_default_python_path_is_platform_aware": {
        "module": "路径运行时",
        "kind": "offline_unit",
        "entry": "scutio_data.paths.default_python_path",
        "feature": "默认 Python 路径区分 Windows 与 Unix",
        "input": "SCUTIO_HOME=/tmp/scutio-home-test，清除 SCUTIO_PYTHON/VENV",
        "expected": "Unix 以 .venv/bin/python 结尾；Windows 以 Scripts/python.exe 结尾",
    },
    "test_path_helpers_importable_from_package_root": {
        "module": "路径运行时",
        "kind": "offline_unit",
        "entry": "scutio_data 根包 re-export",
        "feature": "路径助手可从包根 import",
        "input": "from scutio_data import default_python_path, …",
        "expected": "三者均可调用",
    },
    "test_result_ok_and_result_err_envelope": {
        "module": "返回信封",
        "kind": "offline_unit",
        "entry": "core.result_ok / result_err / result_list",
        "feature": "统一 dict 信封字段契约",
        "input": "result_ok(...); result_list(items); result_list_err(...)",
        "expected": "ok/error/source 字段齐全；成功 items；失败可迭代为空",
    },
    "test_valuation_snapshot_returns_err_envelope_on_quote_failure": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_snapshot",
        "feature": "报价源异常时返回 err 信封而非裸异常冒泡",
        "input": "code=600519，security_quote mock 抛 RuntimeError('network down')",
        "expected": "ok=false；error 含 network down；source=security_quote；code=600519",
    },
    "test_valuation_snapshot_returns_ok_envelope": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_snapshot",
        "feature": "报价成功时返回报价侧估值信封",
        "input": "code=600519，mock security_quote 成功",
        "expected": "ok=true；source=tencent；price/pe_ttm/pb；无 eps 字段",
    },
    "test_valuation_snapshot_uses_security_quote_fallback_when_tencent_empty": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_snapshot",
        "feature": "报价走 security_quote 多源；sina 有价时仍可出快照",
        "input": "security_quote 返回 source=sina 的报价",
        "expected": "ok=true；quote_source=sina；source=sina",
    },
    "test_valuation_snapshot_quote_only_no_eps_fields": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_snapshot",
        "feature": "快照不含一致预期字段",
        "input": "mock 报价成功",
        "expected": "无 eps_cur/pe_fwd/eps_error",
    },
    "test_valuation_history_returns_compact_windows_without_series": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_history",
        "feature": "紧凑返回 3年/5年/可得全期估值分位",
        "input": "mock A 股历史 PE/PB/PS，include_series=false",
        "expected": "无原始序列；窗口、样本数与分位完整",
    },
    "test_valuation_history_falls_back_only_after_primary_failure": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_history",
        "feature": "东财失败后才回退百度",
        "input": "东财抛异常，百度返回 PE/PB 历史",
        "expected": "ok=true；source=baidu_valuation_backup；保留主源错误",
    },
    "test_valuation_history_rejects_non_a_before_fetch": {
        "module": "估值",
        "kind": "offline_mock",
        "entry": "valuation.valuation_history",
        "feature": "港美代码在联网前按能力边界拒绝",
        "input": "usTSM",
        "expected": "ok=false；unsupported_market；不发请求",
    },
    "test_ths_eps_forecast_preserves_provider_columns": {
        "module": "研报/一致预期",
        "kind": "offline_fixture",
        "entry": "research.eps_forecast",
        "feature": "AKShare EPS 表保留逐公司年度及均值、机构数",
        "input": "mock AKShare 每股收益表",
        "expected": "非空表；含均值/机构数；首行均值≈68.70",
    },
    "test_ths_eps_forecast_empty_when_no_coverage": {
        "module": "研报/一致预期",
        "kind": "offline_mock",
        "entry": "research.eps_forecast",
        "feature": "源明确返回空表时保留无覆盖语义",
        "input": "mock AKShare 空列表",
        "expected": "ok=true、items=[]",
    },
    "test_forward_pe_and_peg_pure_formulas": {
        "module": "估值",
        "kind": "offline_unit",
        "entry": "valuation.forward_pe / calc_peg",
        "feature": "纯公式边界",
        "input": "price/eps/cagr 样例",
        "expected": "pe=10；eps<=0 → inf；peg≈1",
    },
    # ── macro ─────────────────────────────────────────────────────
    "test_map_lpr_rows_and_parse_sina_hq": {
        "module": "宏观",
        "kind": "offline_unit",
        "entry": "macro.series.map_lpr_rows / _providers.sina_fx.parse_sina_hq",
        "feature": "LPR 行映射与新浪 hq 解析",
        "input": "mock LPR 行 + fx/hf 字符串",
        "expected": "date/lpr 字段；fx price；空串解析 None",
    },
    "test_lpr_failure_envelope": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.lpr_history",
        "feature": "网络失败 result_list_err ok=False",
        "input": "AKShare fetch 抛 ConnectionError",
        "expected": "空列表 + error",
    },
    "test_rates_snapshot_partial": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.rates_snapshot",
        "feature": "LPR 成功 SHIBOR 失败时 partial",
        "input": "AKShare LPR 成功；SHIBOR 抛错",
        "expected": "ok=true；有 lpr；errors 非空",
    },
    "test_fx_and_commodities_sina": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.fx_usdcny / commodities_spot",
        "feature": "新浪 USDCNY 直连与 AKShare 金油报价",
        "input": "mock 新浪 USDCNY HTTP 与 AKShare 商品表",
        "expected": "USDCNY 与 gold/wti 有 price",
    },
    "test_macro_snapshot_aggregates_legs": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.macro_snapshot",
        "feature": "聚合各腿成功字段",
        "input": "stub rates/bonds/fx/indices/commodities/series",
        "expected": "ok；含 lpr/bonds/fx/indices/commodities",
    },
    "test_macro_snapshot_all_fail": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.macro_snapshot",
        "feature": "全腿失败 ok=False",
        "input": "全部 stub 失败",
        "expected": "ok=false；errors",
    },
    "test_index_board_uses_tencent": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.index_board",
        "feature": "指数板走 tencent_quote",
        "input": "mock 上证报价",
        "expected": "indices[0].price",
    },
    "test_list_macro_series_covers_required_names": {
        "module": "宏观",
        "kind": "offline_unit",
        "entry": "macro.MACRO_SERIES",
        "feature": "P1 序列名齐全",
        "input": "无",
        "expected": "含 cpi/ppi/pmi/m2/loan/export/industrial/retail/fai/gdp",
    },
    "test_currency_supply_m2_m1_m0_field_mapping": {
        "module": "宏观",
        "kind": "offline_mock",
        "entry": "macro.cn_macro_series(m2_yoy)",
        "feature": "AKShare 货币供应的 M2/M1/M0 存量与同比列映射",
        "input": "mock AKShare 中文字段行（M2>M1>M0 存量）",
        "expected": "value=M2同比；m2/m1/m0 与 yoy 字段不错位",
    },
    # ── research_local ─────────────────────────────────────────────
    "test_local_report_search_expands_theme_and_ranks_matches": {
        "module": "研报本地检索",
        "kind": "offline_unit",
        "entry": "research.local_report_search",
        "feature": "主题同义词扩展；匹配分高者排前",
        "input": "查询「人形机器人 行星滚柱丝杠」+ 3 条本地 records",
        "expected": "排序 infoCode=[high, screw]；含匹配词；source=eastmoney_local",
    },
    "test_local_report_search_fetches_eastmoney_records": {
        "module": "研报本地检索",
        "kind": "offline_mock",
        "entry": "research.local_report_search",
        "feature": "默认路径拉取东财行业研报（无密钥）",
        "input": "查询「AI 算力」，begin=2026-01-01，max_pages=2；mock industry_reports",
        "expected": "调用参数 industry=*；结果带 _matched_terms",
    },
    "test_local_report_search_mixed_case_terms_score_positive": {
        "module": "研报本地检索",
        "kind": "offline_unit",
        "entry": "research.local_report_search",
        "feature": "大小写混用词（如 AI）仍贡献分数",
        "input": "含 AI/ai 的 title 与查询",
        "expected": "匹配分 > 0",
    },
    "test_local_stock_screen_supports_aliases_and_missing_sort_values": {
        "module": "本地选股",
        "kind": "offline_unit",
        "entry": "research.local_stock_screen（或等价）",
        "feature": "中文别名过滤；缺排序字段不崩",
        "input": "本地 records + 中文条件/排序字段缺失行",
        "expected": "过滤正确；缺失排序值可排到末尾或跳过且不抛异常",
    },
    "test_local_stock_screen_preserves_input_and_supports_limit_none": {
        "module": "本地选股",
        "kind": "offline_unit",
        "entry": "local_stock_screen",
        "feature": "返回拷贝不改原列表；limit=None 返回全量过滤结果",
        "input": "records + limit=None",
        "expected": "原 input 未变；返回条数=过滤后全集",
    },
    "test_report_detail_url_and_html_extractors": {
        "module": "研报解析",
        "kind": "offline_unit",
        "entry": "_documents.reports 详情 URL / HTML 抽取",
        "feature": "详情 URL 模板与 HTML 抽取器离线稳定",
        "input": "infoCode + 固定 HTML 片段",
        "expected": "URL 形态正确；标题/摘要等字段可抽出",
    },
    "test_download_pdf_prefers_curl_and_validates_magic": {
        "module": "研报 PDF",
        "kind": "offline_mock",
        "entry": "research.download_pdf / _documents.reports",
        "feature": "优先 curl；校验 PDF magic；非 PDF 拒绝",
        "input": "mock curl 成功 PDF 头 / 非 PDF body；tmp 路径",
        "expected": "合法 PDF 落盘；非法 body 失败且不误存",
    },
    "test_report_page_detail_parses_mock_html": {
        "module": "研报解析",
        "kind": "offline_mock",
        "entry": "research.report_page_detail",
        "feature": "详情页 HTML → abstract + pdf_url",
        "input": "mock HTML 页面",
        "expected": "abstract 非空；pdf_url 可解析",
    },
    # ── live_smoke (SCUTIO_LIVE=1) ─────────────────────────────────
    "test_live_tencent_quote": {
        "module": "LIVE 行情",
        "kind": "live_network",
        "entry": "market.tencent_quote",
        "feature": "腾讯实时报价公网通路",
        "input": "600519、000001、sh000001",
        "expected": "dict 非空；茅台/上证有 name 与 price>0",
    },
    "test_live_security_quote_fallback": {
        "module": "LIVE 行情",
        "kind": "live_network",
        "entry": "market.security_quote",
        "feature": "多源报价（腾讯→新浪）真实 fallback",
        "input": "[600519, 000001]",
        "expected": "ok=true；至少一只有效 price；sources_used 非空",
    },
    "test_live_security_bars": {
        "module": "LIVE 行情",
        "kind": "live_network",
        "entry": "market.security_bars",
        "feature": "日 K 真实通路（AKShare 新浪→腾讯→东财）",
        "input": "600519 frequency=D count=5",
        "expected": "ok=true；≥1 根；close>0；记录 source",
    },
    "test_live_security_bars_index": {
        "module": "LIVE 行情",
        "kind": "live_network",
        "entry": "market.security_bars",
        "feature": "上证指数日 K 真实通路",
        "input": "sh000001 index=True count=3",
        "expected": "ok=true；close>0",
    },
    "test_live_eastmoney_stock_info": {
        "module": "LIVE 基本面",
        "kind": "live_network",
        "entry": "fundamentals.stock_info",
        "feature": "东财个股资料（失败可 新浪 finance 回退）",
        "input": "600519",
        "expected": "source≠empty；东财路径有名称/市值或价格",
    },
    "test_live_valuation_snapshot": {
        "module": "LIVE 估值",
        "kind": "live_network",
        "entry": "valuation.valuation_snapshot",
        "feature": "报价侧估值快照（无一致预期）",
        "input": "600519",
        "expected": "ok=true；price>0；name 非空",
    },
    "test_live_valuation_history": {
        "module": "LIVE 估值",
        "kind": "live_network",
        "entry": "valuation.valuation_history",
        "feature": "A 股历史估值主源或备用源",
        "input": "600519 include_series=false",
        "expected": "ok=true；样本>100；PE/PB 至少一项可形成分位",
    },
    "test_live_cninfo_announcements": {
        "module": "LIVE 公告",
        "kind": "live_network",
        "entry": "announcements.stock_announcements",
        "feature": "巨潮公告列表公网",
        "input": "600519 page_size=5",
        "expected": "ok；≥1 条；title/url 非空",
    },
    "test_live_eastmoney_stock_news": {
        "module": "LIVE 新闻",
        "kind": "live_network",
        "entry": "feeds.stock_news",
        "feature": "东财个股新闻搜索",
        "input": "600519 page_size=5",
        "expected": "不报错 ok；有条目则 title 非空",
    },
    "test_live_cls_telegraph": {
        "module": "LIVE 新闻",
        "kind": "live_network",
        "entry": "feeds.telegraph",
        "feature": "财联社电报公网",
        "input": "page_size=5",
        "expected": "≥1 条；title 或 content 非空",
    },
    "test_live_stock_fund_flow_120d": {
        "module": "LIVE 资金",
        "kind": "live_network",
        "entry": "capital.stock_fund_flow_120d",
        "feature": "个股日频资金流 AKShare 通路",
        "input": "600519",
        "expected": "ok；≥1 行；含 date/time",
    },
    "test_live_industry_comparison": {
        "module": "LIVE 资金",
        "kind": "live_network",
        "entry": "capital.industry_comparison",
        "feature": "行业涨跌榜双腿公网",
        "input": "top_n=5",
        "expected": "至少一腿有数据（允许 partial）",
    },
    "test_live_local_report_search": {
        "module": "LIVE 研报",
        "kind": "live_network",
        "entry": "research.local_report_search",
        "feature": "拉东财行业研报并本地打分",
        "input": "query=人工智能 max_pages=1",
        "expected": "不抛异常；有结果则含 title",
    },
    "test_financial_report_rejects_unknown_type_and_period_before_fetch": {
        "module": "基本面契约",
        "kind": "offline_mock",
        "entry": "fundamentals.financial_report",
        "feature": "非法类型/周期在联网前失败",
        "input": "cashfow / quater",
        "expected": "ok=false 且未调用上游",
    },
    "test_security_quote_mixed_invalid_code_is_partial": {
        "module": "行情契约",
        "kind": "offline_mock",
        "entry": "market.security_quote",
        "feature": "混合批次不吞非法代码",
        "input": "600519 + BAD",
        "expected": "ok=true partial=true；invalid/missing 完整",
    },
    "test_a_only_facades_reject_hk_us_without_network": {
        "module": "市场边界",
        "kind": "offline_mock",
        "entry": "core.require_market",
        "feature": "A 专属能力前置拦截港美",
        "input": "A 股专属门面",
        "expected": "unsupported_market 且零网络调用",
    },
    "test_package_root_does_not_export_transport_internals": {
        "module": "包边界",
        "kind": "offline_unit",
        "entry": "scutio_data.__all__",
        "feature": "包根不平铺传输实现",
        "input": "检查导出表",
        "expected": "无 EM_SESSION/em_get/单源函数",
    },
    "test_reports_local_example_unwraps_items": {
        "module": "示例",
        "kind": "offline_mock",
        "entry": "examples/03_reports_local.py",
        "feature": "研报示例解包 result_list",
        "input": "fixture 信封",
        "expected": "执行成功",
    },
    "test_trade_calendar_primary_and_historical_backup": {
        "module": "P0 交易日历",
        "kind": "offline_mock",
        "entry": "events.trade_calendar",
        "feature": "交易所规则主路径与历史 K 线 backup",
        "input": "A 股单日",
        "expected": "主源成功；失败时 backup_used/partial",
    },
    "test_earnings_calendar_failure_is_not_empty_success": {
        "module": "P0 事件日历",
        "kind": "offline_mock",
        "entry": "events.earnings_calendar",
        "feature": "预约披露请求失败不返回空表成功",
        "input": "2026 半年报，AKShare 失败",
        "expected": "ok=false、items=[]",
    },
    "test_suspension_and_earnings_mappers_do_not_use_column_order_for_em": {
        "module": "P0 事件日历",
        "kind": "offline_unit",
        "entry": "events.map_*",
        "feature": "停复牌/预约披露按字段映射",
        "input": "乱序 dict",
        "expected": "原因与最后预约日正确",
    },
    "test_market_breadth_counts_and_sina_fallback": {
        "module": "P1 市场宽度",
        "kind": "offline_mock",
        "entry": "breadth.market_breadth",
        "feature": "涨跌家数与新浪 backup",
        "input": "涨/跌/平各一",
        "expected": "计数正确；东财失败切新浪",
    },
    "test_index_constituent_official_partial_weights_and_backup": {
        "module": "P1 指数成分",
        "kind": "offline_mock",
        "entry": "breadth.index_constituents",
        "feature": "权重单腿 partial 与新浪 backup",
        "input": "000300",
        "expected": "成分保留；权重错误显式",
    },
    "test_consensus_forecast_and_revision_contract": {
        "module": "P0 一致预期",
        "kind": "offline_mock",
        "entry": "research.consensus_*",
        "feature": "东财→同花顺与逐机构修订",
        "input": "600519",
        "expected": "标准 EPS；相邻研报识别上调",
    },
    "test_structured_corporate_actions_and_partial_aggregation": {
        "module": "P1 公司行动",
        "kind": "offline_mock",
        "entry": "capital.corporate_actions",
        "feature": "回购字段与组合 partial",
        "input": "600519",
        "expected": "实施中；单腿失败保留其余腿",
    },
    "test_macro_surprise_and_actual_only_fallback": {
        "module": "P2 宏观日历",
        "kind": "offline_mock",
        "entry": "macro.macro_surprises",
        "feature": "实际-预期与 actual-only 降级",
        "input": "CPI",
        "expected": "surprise=0.5；备源 surprise=None",
    },
    "test_economic_calendar_supports_bounded_upcoming_window": {
        "module": "P2 宏观日历",
        "kind": "offline_mock",
        "entry": "macro.economic_calendar",
        "feature": "未来事件短窗口",
        "input": "未来 3 日",
        "expected": "逐日聚合且保留 surprise",
    },
}

KIND_LABEL = {
    "offline_unit": "离线 · 单元",
    "offline_test": "离线 · 回归",
    "offline_mock": "离线 · mock",
    "offline_fixture": "离线 · fixture",
    "live_network": "真实公网",
}

STATUS_LABEL = {
    "passed": "✅ 通过",
    "failed": "❌ 失败",
    "skipped": "⏭ 跳过",
    "error": "💥 错误",
    "xfailed": "⚠ 预期失败",
    "xpassed": "⚠ 意外通过",
}


# 未逐条补充业务说明的用例按文件归组，报告保留完整 nodeid 直达实际断言。
# 分组说明表示该文件的覆盖范围，不冒充每个 case 的输入和断言。
CASE_GROUPS: dict[str, tuple[str, str]] = {
    "data/test_batch.py": ("批量取数", "同步终态、独立预算、上下文、进度与取消"),
    "data/test_batch_domains.py": ("领域组合", "独立取数腿并发、依赖复用和部分覆盖"),
    "data/test_execution.py": ("来源执行", "跨进程配额、缓存复用、故障隔离与恢复探测"),
    "data/test_screen_records.py": ("程序筛选", "显式样本、条件计算、覆盖范围与缺失项"),
    "data/test_request_timeouts.py": ("取数超时", "共享预算、缓慢响应取消、队列、回退与可选状态锁"),
    "data/test_research_scope.py": ("研究数据范围", "保留能力、删除入口与频率边界"),
    "data/test_api_contracts.py": ("接口契约", "代码身份、返回信封、缺失字段与来源回退"),
    "data/test_exchange_ids.py": ("证券身份", "A/港/美代码与源证券映射"),
    "data/test_security_identity.py": ("证券身份边界", "公司入口、指数/基金、交易所与回退响应身份"),
    "data/test_ownership_filings.py": ("美股股权披露", "SEC 新旧 13D/13G 表单与修订"),
    "data/test_hk_us_market.py": ("港美行情", "市场路由、单位、日期连续性和覆盖范围"),
    "data/test_hk_us_financials.py": ("港美财报", "报表类型、报告期与原生科目"),
    "data/test_optional_sources.py": (
        "可选数据服务",
        "凭据隔离、权限冷却、缓存、严格选源与免费回退",
    ),
    "data/test_akshare_market_contracts.py": (
        "AKShare 行情契约",
        "代码身份、OHLC 缺失与非有限数值、成交量、复权与市场覆盖",
    ),
    "data/test_akshare_maintenance.py": (
        "AKShare 版本检查",
        "连续失败分类、冷却、兼容版本与不自动安装",
    ),
    "data/test_akshare_network.py": ("AKShare 网络", "代理恢复、共享时限、停用接口与错误脱敏"),
    "data/test_capital_history.py": ("历史资金与事件", "时间分区、截断、单位、预算和部分失败"),
    "data/test_content_adapters.py": (
        "内容适配",
        "新闻窗口、互动分页、快报与字段单位",
    ),
    "data/test_dragon_tiger_and_calendars.py": (
        "龙虎榜与日历",
        "上榜原因、席位完整性、停牌计划和预约变更",
    ),
    "data/test_source_contracts.py": ("源字段契约", "快照缓存、身份核对、原文解析、单位和空值"),
    "data/test_source_semantics.py": ("数据口径", "财报科目、宏观单位及时效、原文身份与请求预算"),
    "data/test_data_architecture.py": ("取数层边界", "导入隔离、worker 启动、宏观复用和原文归属"),
    "data/test_data_audit_regressions.py": ("数据审计回归", "完整财报、行情单位和特别分红"),
    "data/test_macro.py": ("宏观", "序列路由、单位、指数身份与缺项、快照部分覆盖"),
    "data/test_p0_p2_data.py": ("研究数据契约", "事件、市场宽度、公司行动与宏观聚合"),
    "data/test_evidence_reuse.py": ("材料复用", "证券身份、财年、时点、覆盖与 PDF 直链"),
    "data/test_research_pagination.py": ("研报分页", "非个股列表分页、部分失败与检索覆盖"),
    "data/test_research_local.py": ("研报检索", "评分、去重、市值筛选、在线身份与时效覆盖"),
    "data/test_ths_eps_and_valuation.py": ("估值与一致预期", "EPS 原生字段、历史估值与报价复用"),
    "data/test_live_smoke.py": ("公网通路", "公开数据门面可用性；需显式启用网络"),
}

LAYER_LABELS = {"journal": "研究记录", "runtime": "运行时与文档"}


def lookup(nodeid: str) -> dict[str, Any]:
    """从 pytest nodeid 取元数据；未知 case 给兜底说明。"""
    name = nodeid.split("::")[-1]
    base = name.split("[", 1)[0]
    meta = CASES.get(base)
    if meta:
        return {"name": base, "nodeid": nodeid, **meta}
    path = nodeid.split("::", 1)[0].replace("\\", "/")
    relative = path.split("tests/", 1)[-1]
    group = CASE_GROUPS.get(relative)
    layer = relative.split("/", 1)[0]
    module, scope = group or (LAYER_LABELS.get(layer, "未分类"), "测试源码中的行为与断言")
    return {
        "name": base,
        "nodeid": nodeid,
        "module": module,
        "kind": "live_network" if relative == "data/test_live_smoke.py" else "offline_test",
        "entry": relative,
        "feature": f"{scope}；用例：{base.removeprefix('test_')}",
        "input": "见测试源码",
        "expected": "见测试断言",
    }
